spring.application.name=milktea_backend
server.port=8080

# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/milktea_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=130405
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# Vi ban da tao san DB bang file SQL, o day dung 'update' hoac 'none'
spring.jpa.hibernate.ddl-auto=update
# In ra cau lenh SQL de de debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

app.admin.password=${ADMIN_PASSWORD:123456}

# ===============================
# JWT CONFIGURATION
# ===============================
# Chu?i bí m?t (Secret Key) - Yêu c?u b?t bu?c: Ph?i dài ít nh?t 32 ký t? (256-bit) cho thu?t toán HS256
app.jwt.secret=${JWT_SECRET:DayLaChuoiBiMatSieuDaiCuaDuAnTraSuaGiaDinh2026SieuBaoMat}

# Th?i gian s?ng c?a Token (tính b?ng milliseconds) - VD: 86400000 = 24 gi?
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# ===============================
# EMAIL SMTP CONFIGURATION (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anh2005.tranvan@gmail.com
spring.mail.password=mtqp iheq rujn qali
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Link Frontend ?? Backend chuy?n h??ng (Redirect) v? sau khi xác th?c thành công
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# ==========================================
# C?U HÌNH PAYMENT WEBHOOK (SEPAY)
# ==========================================
sepay.webhook.api-key=milktea-130405